language: groovy

env:
  global:
    - GRADLE_OPTS=-Xmx1524m

jdk:
  - oraclejdk8
  - oraclejdk11

script:
  - java -version
  - gradle -version
  - gradle --stop
  - gradle --refresh-dependencies clean check -Dscan --info 