language: groovy

env:
  global:
    - GRADLE_OPTS=-Xmx1500m

jdk:
  - oraclejdk8

script:
  - java -version
  - gradle -version
  - gradle --stop
  - gradle --refresh-dependencies clean check -Dscan --info